library(tidyverse)
library(ggplot2)
confdata <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")
deathdata <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")
beddata <- read.csv('C:/Users/luked/Downloads/WHS6_102.csv')
demodata <- read.csv("C:/Users/luked/Downloads/demographics.csv")
beddata <- beddata %>% mutate(Country = replace(Country, Country == "United Kingdom of Great Britain and Northern Ireland", "United Kingdom"))
beddata <- beddata %>% mutate(Country = replace(Country, Country == "Iran (Islamic Republic of)", "Iran"))
beddata <- beddata %>% mutate(Country = replace(Country, Country == "Republic of Korea", "South Korea"))
beddata <- beddata %>% rename(beds = Hospital.beds..per.10.000.population.)
updbeddata <- beddata %>% group_by(Country) %>% filter(Year==max(Year))
confdata <- confdata %>% rename(Country = Country.Region)
deathdata <- deathdata %>% rename(Country = Country.Region)
confdata1 <- confdata %>% select(2,5:440)
deathdata1 <- deathdata %>% select(2,5:440)
confdata2 <- confdata1 %>% group_by(Country) %>% summarise(across(2:436,sum))
deathdata2 <- deathdata1 %>% group_by(Country) %>% summarise(across(2:436,sum))
coviddata <- deathdata3 %>% inner_join(confdata3)
coviddata <- coviddata %>% mutate(Country = replace(Country, Country == "Korea, South", "South Korea"))
covidBed <- coviddata %>% inner_join(updbeddata)
covidBed <- covidBed %>% select(1:4, 6)
demodata <- demodata %>% rename(Country = ï..Country.Name)
demodata <- demodata %>% mutate(Country = replace(Country, Country == "Korea, Rep.", "South Korea"))
demodata <- demodata %>% mutate(Country = replace(Country, Country == "Iran, Islamic Rep.", "Iran"))
popdata <- demodata %>% filter(!Series.Code == 'SP.DYN.LE00.IN', !Series.Code == 'SP.URB.TOTL', !Series.Code =='SP.DYN.AMRT.FE', !Series.Code == 'SP.DYN.AMRT.MA', !Series.Code == 'SP.POP.TOTL.FE.IN', !Series.Code == 'SP.POP.TOTL.MA.IN')
pop14 <- popdata %>% filter(Series.Code=='SP.POP.0014.MA.IN'| Series.Code=='SP.POP.0014.FE.IN')
pop1564 <- popdata %>% filter(Series.Code=='SP.POP.1564.MA.IN'| Series.Code=='SP.POP.1564.FE.IN')
pop65up <- popdata %>% filter(Series.Code=='SP.POP.65UP.MA.IN'| Series.Code=='SP.POP.65UP.FE.IN')
pop80up <- popdata %>% filter(Series.Code=='SP.POP.80UP.MA'| Series.Code=='SP.POP.80UP.FE')
poptotal <- popdata %>% filter(Series.Code=='SP.POP.TOTL')
pop14$YR2015 <- as.integer(pop14$YR2015)
pop1564$YR2015 <- as.integer(pop1564$YR2015)
pop65up$YR2015 <- as.integer(pop65up$YR2015)
pop80up$YR2015 <- as.integer(pop80up$YR2015)
poptotal$YR2015 <- as.integer(poptotal$YR2015)
pop14 <- pop14 %>% group_by(Country) %>% summarise(Total=sum(YR2015, na.rm = TRUE))
pop1564 <- pop1564 %>% group_by(Country) %>% summarise(Total=sum(YR2015, na.rm = TRUE))
pop65up <- pop65up %>% group_by(Country) %>% summarise(Total=sum(YR2015, na.rm = TRUE))
pop80up <- pop80up %>% group_by(Country) %>% summarise(Total=sum(YR2015, na.rm = TRUE))
pop14 <- pop14 %>% rename(POP.0014=Total)
pop1564 <- pop1564 %>% rename(POP.1564=Total)
pop65up <- pop65up %>% rename(POP.65.UP=Total)
pop80up <- pop80up %>% rename(POP.80.UP=Total)
poptotal <- poptotal %>% rename(POP.TOTL=YR2015)
covidBed <- covidBed %>% inner_join(poptotal)
covidBed <- covidBed %>% inner_join(pop80up)
covidBed <- covidBed %>% inner_join(pop65up)
covidBed <- covidBed %>% inner_join(pop1564)
covidBed <- covidBed %>% inner_join(pop14)
covidBed <- covidBed %>% select(1:5, 9:13)

mod1 <- lm(deaths ~ beds+POP.80.UP+POP.65.UP+POP.1564+POP.0014, data=covidBed)
mod2 <- lm(deaths ~ confirmed+beds+POP.80.UP+POP.65.UP, data=covidBed)
mod3 <- lm(deaths ~ confirmed+beds+POP.TOTL+POP.80.UP+POP.65.UP, data=covidBed)
mod4 <- lm(deaths ~ confirmed+POP.80.UP+POP.65.UP+POP.1564+POP.0014, data=covidBed)
mod5 <- lm(deaths ~ confirmed+beds+POP.80.UP+POP.65.UP+POP.1564+POP.0014, data=covidBed)

R2values <- c(summary(mod1)$adj.r.squared, summary(mod2)$adj.r.squared, summary(mod3)$adj.r.squared, summary(mod4)$adj.r.squared, summary(mod5)$adj.r.squared)
models <- c('beds+POP.80.UP+POP.65.UP+POP.1564+POP.0014', 
            'confirmed+beds+POP.80.UP+POP.65.UP',
            'confirmed+beds+POP.TOTL+POP.80.UP+POP.65.UP',
            'confirmed+POP.80.UP+POP.65.UP+POP.1564+POP.0014',
            'confirmed+beds+POP.80.UP+POP.65.UP+POP.1564+POP.0014')
models <- factor(models, levels=c('beds+POP.80.UP+POP.65.UP+POP.1564+POP.0014', 
                                  'confirmed+beds+POP.80.UP+POP.65.UP',
                                  'confirmed+beds+POP.TOTL+POP.80.UP+POP.65.UP',
                                  'confirmed+POP.80.UP+POP.65.UP+POP.1564+POP.0014',
                                  'confirmed+beds+POP.80.UP+POP.65.UP+POP.1564+POP.0014'))
Models <- c('m1','m2','m3','m4','m5')
R2s <- data.frame(models, R2values)
# The ggplot code needs to be ran manually for the bars to show
ggplot(data=R2s, aes(x=Models, y=R2values, fill=models))+geom_bar(stat='identity')

